#include <Arduino.h>
#include <HTTPClient.h>
#include <Preferences.h>
#include <SPI.h>
#include <WiFi.h>
#include <WiFiClientSecure.h>
#include <esp_sleep.h>
#include <cctype>
#include <cstdlib>
#include <cstdarg>
#include <ctime>
#include <cstring>

#include <ArduinoJson.h>
#include <Fonts/FreeMono9pt7b.h>
#include <Fonts/FreeMonoBold18pt7b.h>
#include <GxEPD2_BW.h>
#include <Update.h>

#include "config.h"
#include "firmware_version.h"  // generated by scripts/pre_build_version.py

// ESP32-S3 DevKitM-1 -> Waveshare 2.9" e-paper (296x128)
static constexpr uint8_t EPD_CS   = 7;
static constexpr uint8_t EPD_DC   = 6;
static constexpr uint8_t EPD_RST  = 5;
static constexpr uint8_t EPD_BUSY = 4;
static constexpr uint8_t EPD_SCK  = 12;
static constexpr uint8_t EPD_MOSI = 11;

static constexpr uint32_t WIFI_TIMEOUT_MS      = 20000;
static constexpr uint32_t HTTP_TIMEOUT_MS      = 12000;
static constexpr uint8_t  RGB_LED_BRIGHTNESS   = 40;
static constexpr uint32_t RGB_LED_STEP_MS      = 12;
static constexpr uint32_t RGB_SPECTRUM_PERIOD_MS = 12000;
static constexpr bool     CONTINUOUS_RGB_MODE  = true;
static constexpr int16_t  RGB_LED_PIN          = RGB_LED_DATA_PIN;
static constexpr int16_t  RGB_LED_PWR_PIN      = RGB_LED_POWER_PIN;

// Minimum epoch considered a valid synced time.
// Derived from the build date so it automatically advances with each firmware build.
// __DATE__ format: "Mmm DD YYYY"
static time_t buildDateEpoch() {
  const char *d = __DATE__;
  int year = (d[7]-'0')*1000 + (d[8]-'0')*100 + (d[9]-'0')*10 + (d[10]-'0');
  int day  = (d[4]==' ' ? 0 : (d[4]-'0')) * 10 + (d[5]-'0');
  int mon  = 1;
  if      (d[0]=='J' && d[1]=='a') mon = 1;
  else if (d[0]=='F')               mon = 2;
  else if (d[0]=='M' && d[2]=='r') mon = 3;
  else if (d[0]=='A' && d[1]=='p') mon = 4;
  else if (d[0]=='M' && d[2]=='y') mon = 5;
  else if (d[0]=='J' && d[2]=='n') mon = 6;
  else if (d[0]=='J' && d[2]=='l') mon = 7;
  else if (d[0]=='A' && d[1]=='u') mon = 8;
  else if (d[0]=='S')               mon = 9;
  else if (d[0]=='O')               mon = 10;
  else if (d[0]=='N')               mon = 11;
  else                               mon = 12;
  struct tm t = {};
  t.tm_year = year - 1900;
  t.tm_mon  = mon - 1;
  t.tm_mday = day;
  t.tm_isdst = -1;
  time_t epoch = mktime(&t);
  // mktime uses local time; subtract UTC offset to get UTC epoch
  return (epoch > 0) ? epoch : (time_t)1741000000L; // fallback: March 2025
}
// Initialised once in setup() to avoid calling mktime at static-init time
static time_t MIN_VALID_EPOCH = 1741000000L;

// Screen IDs
static constexpr uint8_t SCREEN_WEATHER = 0;
static constexpr uint8_t SCREEN_MARKET  = 1;
static constexpr uint8_t SCREEN_THOUGHT = 2;
static constexpr uint8_t SCREEN_FOCUS   = 3;
static constexpr uint8_t SCREEN_PRAYER  = 4;
static constexpr uint8_t SCREEN_NEWS    = 5;
static constexpr uint8_t MAX_SCREENS    = 6;

GxEPD2_BW<GxEPD2_290_T94_V2, GxEPD2_290_T94_V2::HEIGHT> display(
    GxEPD2_290_T94_V2(EPD_CS, EPD_DC, EPD_RST, EPD_BUSY));

// ---------------------------------------------------------------------------
// Data structures
// ---------------------------------------------------------------------------

struct WeatherData {
  bool    valid;
  float   temperatureC;
  float   apparentTemperatureC;
  float   humidityPercent;
  float   uvIndex;
  int     rainChancePercent;
  uint16_t weatherCode;
};

struct MarketData {
  bool  valid;
  bool  hasBtc, hasEth, hasGold, hasOil, hasZarUsd, hasZarMur;
  float btcUsd, ethUsd, goldUsd, oilUsd, zarUsd, zarMur;
  char  error[256];
};

struct ThoughtData {
  bool valid;
  char text[256];
  char source[48];
  char error[96];
};

struct PrayerData {
  bool valid;
  char fajr[8];
  char dhuhr[8];
  char asr[8];
  char maghrib[8];
  char isha[8];
  char date[16];
  char error[96];
};

struct NewsData {
  bool valid;
  char headline[200];
  char source[48];
  char score[20];
  char error[96];
};

// ---------------------------------------------------------------------------
// RTC-persistent variables (survive deep sleep)
// ---------------------------------------------------------------------------
RTC_DATA_ATTR uint32_t    bootCount      = 0;
RTC_DATA_ATTR MarketData  lastMarketData = {false,false,false,false,false,false,false,
                                            0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,""};
RTC_DATA_ATTR WeatherData cachedWeather  = {false,0.0f,0.0f,0.0f,-1.0f,-1,65535};
RTC_DATA_ATTR time_t      weatherFetchedAt = 0;
RTC_DATA_ATTR PrayerData  cachedPrayer   = {false,"","","","","","",""};
RTC_DATA_ATTR time_t      prayerFetchedDay = 0; // epoch of midnight on fetch day
RTC_DATA_ATTR NewsData    cachedNews     = {false,"","","",""};
RTC_DATA_ATTR uint8_t     screenList[MAX_SCREENS] = {0,1,2,3,4,5};
RTC_DATA_ATTR uint8_t     screenCount    = 0; // 0 = not yet built
RTC_DATA_ATTR time_t      lastOtaCheckTime = 0; // epoch of last OTA version check

static uint8_t  activeCycle         = 0;
static uint32_t lastCycleRefreshMs  = 0;
static bool     continuousModeActive = false;

// ---------------------------------------------------------------------------
// Logging
// ---------------------------------------------------------------------------

void logLine(const char *msg) {
  char line[272];
  snprintf(line, sizeof(line), "[%10lu ms] %s", (unsigned long)millis(), msg);
  Serial.println(line);
  Serial0.println(line);
}

void logf(const char *fmt, ...) {
  char buf[224];
  va_list args;
  va_start(args, fmt);
  vsnprintf(buf, sizeof(buf), fmt, args);
  va_end(args);
  logLine(buf);
}

// ---------------------------------------------------------------------------
// RGB LED
// ---------------------------------------------------------------------------

void setRgbLed(uint8_t r, uint8_t g, uint8_t b) {
  if (RGB_LED_PIN < 0) return;
  neopixelWrite((uint8_t)RGB_LED_PIN, r, g, b);
}

void hueToRgb(uint16_t hue, uint8_t &r, uint8_t &g, uint8_t &b) {
  uint8_t seg = (uint8_t)(hue / 256U);
  uint8_t x   = (uint8_t)(hue % 256U);
  switch (seg) {
    case 0: r=255; g=x;   b=0;   break;
    case 1: r=255-x; g=255; b=0; break;
    case 2: r=0;   g=255; b=x;   break;
    case 3: r=0;   g=255-x; b=255; break;
    case 4: r=x;   g=0;   b=255; break;
    default:r=255; g=0;   b=255-x; break;
  }
}

void setSpectrumHue(uint16_t hue) {
  uint8_t r=0, g=0, b=0;
  hueToRgb(hue, r, g, b);
  r = (uint8_t)((r * RGB_LED_BRIGHTNESS) / 255U);
  g = (uint8_t)((g * RGB_LED_BRIGHTNESS) / 255U);
  b = (uint8_t)((b * RGB_LED_BRIGHTNESS) / 255U);
  setRgbLed(r, g, b);
}

void updateContinuousRgb() {
  if (RGB_LED_PIN < 0) return;
  uint32_t phaseMs = millis() % RGB_SPECTRUM_PERIOD_MS;
  uint16_t hue = (uint16_t)((phaseMs * 1536UL) / RGB_SPECTRUM_PERIOD_MS) % 1536U;
  setSpectrumHue(hue);
}

void runRgbSpectrum(uint32_t durationMs) {
  if (durationMs == 0 || RGB_LED_PIN < 0) return;
  uint32_t startMs = millis();
  while (millis() - startMs < durationMs) {
    uint32_t elapsed = millis() - startMs;
    uint16_t hue = (uint16_t)((elapsed * 1536UL) / durationMs) % 1536U;
    setSpectrumHue(hue);
    delay(RGB_LED_STEP_MS);
  }
  setRgbLed(0, 0, 0);
}

void initRgbLed() {
  logf("RGB init. dataPin=%d powerPin=%d", (int)RGB_LED_PIN, (int)RGB_LED_PWR_PIN);
  if (RGB_LED_PWR_PIN >= 0) {
    pinMode((uint8_t)RGB_LED_PWR_PIN, OUTPUT);
    digitalWrite((uint8_t)RGB_LED_PWR_PIN, RGB_LED_POWER_ON);
  }
  setRgbLed(0, 0, 0);
}

// ---------------------------------------------------------------------------
// Screen list
// ---------------------------------------------------------------------------

void buildScreenList() {
  screenCount = 0;
  if (ENABLE_WEATHER_SCREEN)  screenList[screenCount++] = SCREEN_WEATHER;
  if (ENABLE_MARKET_SCREEN)   screenList[screenCount++] = SCREEN_MARKET;
  if (ENABLE_THOUGHTS_SCREEN) screenList[screenCount++] = SCREEN_THOUGHT;
  if (ENABLE_FOCUS_SCREEN)    screenList[screenCount++] = SCREEN_FOCUS;
  if (ENABLE_PRAYER_SCREEN)   screenList[screenCount++] = SCREEN_PRAYER;
  if (ENABLE_NEWS_SCREEN)     screenList[screenCount++] = SCREEN_NEWS;
  if (screenCount == 0) {
    // Fallback: always show weather
    screenList[screenCount++] = SCREEN_WEATHER;
  }
  logf("Screen list built: %u screens", (unsigned)screenCount);
  for (uint8_t i = 0; i < screenCount; ++i) {
    logf("  screen[%u] = %u", (unsigned)i, (unsigned)screenList[i]);
  }
}

uint32_t getIntervalForScreen(uint8_t screenId) {
  switch (screenId) {
    case SCREEN_WEATHER: return WEATHER_SCREEN_INTERVAL_SEC;
    case SCREEN_MARKET:  return MARKET_SCREEN_INTERVAL_SEC;
    case SCREEN_THOUGHT: return THOUGHTS_SCREEN_INTERVAL_SEC;
    case SCREEN_FOCUS:   return FOCUS_SCREEN_INTERVAL_SEC;
    case SCREEN_PRAYER:  return PRAYER_SCREEN_INTERVAL_SEC;
    case SCREEN_NEWS:    return NEWS_SCREEN_INTERVAL_SEC;
    default:             return WEATHER_SCREEN_INTERVAL_SEC;
  }
}

// ---------------------------------------------------------------------------
// Wi-Fi + Clock
// ---------------------------------------------------------------------------

const char *wakeupCauseStr(esp_sleep_wakeup_cause_t cause) {
  switch (cause) {
    case ESP_SLEEP_WAKEUP_UNDEFINED: return "UNDEFINED";
    case ESP_SLEEP_WAKEUP_TIMER:     return "TIMER";
    case ESP_SLEEP_WAKEUP_EXT0:      return "EXT0";
    case ESP_SLEEP_WAKEUP_EXT1:      return "EXT1";
    case ESP_SLEEP_WAKEUP_TOUCHPAD:  return "TOUCHPAD";
    case ESP_SLEEP_WAKEUP_ULP:       return "ULP";
    case ESP_SLEEP_WAKEUP_GPIO:      return "GPIO";
    case ESP_SLEEP_WAKEUP_UART:      return "UART";
    default:                         return "OTHER";
  }
}

// Persist WiFi credentials to NVS so OTA-updated firmware (which has no
// compiled-in credentials) can still connect on subsequent boots.
static void saveWiFiCredsToNVS(const char* ssid, const char* password) {
  Preferences prefs;
  prefs.begin("wifi", false);
  prefs.putString("ssid", ssid);
  prefs.putString("pass", password);
  prefs.end();
}

static bool loadWiFiCredsFromNVS(String& ssid, String& password) {
  Preferences prefs;
  prefs.begin("wifi", true);
  ssid     = prefs.getString("ssid", "");
  password = prefs.getString("pass", "");
  prefs.end();
  return ssid.length() > 0;
}

bool connectWiFi() {
  if (WiFi.status() == WL_CONNECTED) {
    logf("Wi-Fi already connected. IP=%s RSSI=%d dBm",
         WiFi.localIP().toString().c_str(), WiFi.RSSI());
    return true;
  }

  // Determine which credentials to use.
  // If compiled-in creds are real, use them and persist to NVS for future
  // OTA-updated firmware that won't have creds compiled in.
  String ssid, password;
  const bool compiledCreds = (strcmp(WIFI_SSID, "YOUR_WIFI_SSID") != 0);
  if (compiledCreds) {
    ssid     = WIFI_SSID;
    password = WIFI_PASSWORD;
    saveWiFiCredsToNVS(WIFI_SSID, WIFI_PASSWORD);
    logf("Wi-Fi: using compiled-in creds, saved to NVS. SSID='%s'", ssid.c_str());
  } else if (loadWiFiCredsFromNVS(ssid, password)) {
    logf("Wi-Fi: using NVS creds. SSID='%s'", ssid.c_str());
  } else {
    logf("Wi-Fi: no credentials available (no compiled-in, no NVS). Skipping.");
    return false;
  }

  logf("Wi-Fi connect start. SSID='%s'", ssid.c_str());
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid.c_str(), password.c_str());

  const uint32_t started = millis();
  uint32_t lastLogMs = 0;
  while (WiFi.status() != WL_CONNECTED && millis() - started < WIFI_TIMEOUT_MS) {
    if ((millis() - lastLogMs) > 1000) {
      logf("Wi-Fi waiting... elapsed=%lu ms", (unsigned long)(millis() - started));
      lastLogMs = millis();
    }
    delay(250);
  }
  const bool ok = WiFi.status() == WL_CONNECTED;
  if (ok) {
    logf("Wi-Fi connected. IP=%s RSSI=%d dBm",
         WiFi.localIP().toString().c_str(), WiFi.RSSI());
  } else {
    logf("Wi-Fi connect timeout after %lu ms", (unsigned long)(millis() - started));
  }
  return ok;
}

void syncClock() {
  logf("NTP sync start. UTC offset=%d", UTC_OFFSET_SECONDS);
  configTime(UTC_OFFSET_SECONDS, 0, "pool.ntp.org", "time.google.com", "time.nist.gov");

  time_t now = 0;
  const uint32_t started = millis();
  while (now < MIN_VALID_EPOCH && millis() - started < 15000) {
    time(&now);
    if (((millis() - started) % 2000) < 200) {
      logf("NTP waiting... now=%lld elapsed=%lu ms",
           (long long)now, (unsigned long)(millis() - started));
    }
    delay(200);
  }

  if (now > MIN_VALID_EPOCH) {
    struct tm timeinfo;
    localtime_r(&now, &timeinfo);
    char buf[32];
    strftime(buf, sizeof(buf), "%Y-%m-%d %H:%M:%S", &timeinfo);
    logf("NTP sync ok. Local: %s", buf);
  } else {
    logf("NTP sync failed after %lu ms", (unsigned long)(millis() - started));
  }
}

bool hasValidTime() {
  time_t now;
  time(&now);
  return now > MIN_VALID_EPOCH;
}

// ---------------------------------------------------------------------------
// HTTP helper with retry
// ---------------------------------------------------------------------------

bool httpGetRetry(const char *tag, const String &url, String &payload,
                  int &codeOut, int maxRetries = 3, const char *authToken = nullptr) {
  for (int attempt = 1; attempt <= maxRetries; ++attempt) {
    logf("%s attempt %d/%d URL: %s", tag, attempt, maxRetries, url.c_str());
    payload = "";
    codeOut = 0;

    WiFiClientSecure client;
    client.setInsecure();
    HTTPClient http;
    http.setTimeout(HTTP_TIMEOUT_MS);
    http.setFollowRedirects(HTTPC_FORCE_FOLLOW_REDIRECTS);
    if (!http.begin(client, url)) {
      logf("%s begin() failed", tag);
      if (attempt < maxRetries) { delay(1000 * attempt); continue; }
      return false;
    }
    http.addHeader("User-Agent", "EpaperDashboard/2.0");
    http.addHeader("Accept", "application/json");
    http.addHeader("Accept-Encoding", "identity");
    if (authToken && authToken[0] != '\0') {
      http.addHeader("Authorization", String("Bearer ") + authToken);
    }

    const int code = http.GET();
    codeOut = code;
    logf("%s HTTP %d", tag, code);

    if (code <= 0) {
      logf("%s transport error: %s", tag, http.errorToString(code).c_str());
      http.end();
      if (attempt < maxRetries) { delay(1000 * attempt); continue; }
      return false;
    }

    payload = http.getString();
    http.end();
    logf("%s payload bytes: %u", tag, (unsigned)payload.length());

    if (code != HTTP_CODE_OK) {
      logf("%s non-200: %d", tag, code);
      if (payload.length() > 0) {
        logf("%s error body: %s", tag, payload.substring(0, 160).c_str());
      }
      if (attempt < maxRetries) { delay(1000 * attempt); continue; }
      return false;
    }
    return true;
  }
  return false;
}

// ---------------------------------------------------------------------------
// Weather
// ---------------------------------------------------------------------------

void resetWeatherData(WeatherData &w) {
  w.valid = false;
  w.temperatureC = 0.0f;
  w.apparentTemperatureC = 0.0f;
  w.humidityPercent = 0.0f;
  w.uvIndex = -1.0f;
  w.rainChancePercent = -1;
  w.weatherCode = 65535;
}

bool fetchWeatherOpenMeteo(WeatherData &weather) {
  String url = "https://api.open-meteo.com/v1/forecast?latitude=";
  url += String(WEATHER_LATITUDE, 4);
  url += "&longitude=";
  url += String(WEATHER_LONGITUDE, 4);
  url += "&current=temperature_2m,apparent_temperature,weather_code,"
         "relative_humidity_2m,uv_index";
  url += "&hourly=precipitation_probability&forecast_days=1&timezone=auto";

  String payload;
  int code = 0;
  if (!httpGetRetry("Weather[OpenMeteo]", url, payload, code)) {
    return false;
  }

  JsonDocument doc;
  if (deserializeJson(doc, payload)) { return false; }

  JsonVariant current = doc["current"];
  if (current.isNull()) return false;

  weather.temperatureC         = current["temperature_2m"] | 0.0f;
  weather.apparentTemperatureC = current["apparent_temperature"] | 0.0f;
  weather.humidityPercent      = current["relative_humidity_2m"] | 0.0f;
  weather.uvIndex              = current["uv_index"] | -1.0f;
  weather.weatherCode          = (uint16_t)(current["weather_code"] | 65535);

  JsonVariant rainVal = doc["hourly"]["precipitation_probability"][0];
  if (!rainVal.isNull()) {
    int r = (int)(rainVal | -1);
    weather.rainChancePercent = (r < 0) ? -1 : (r > 100 ? 100 : r);
  }

  weather.valid = true;
  logf("Weather ok: %.1fC feels %.1fC hum %.0f%% uv %.1f rain %d%% code %u",
       weather.temperatureC, weather.apparentTemperatureC,
       weather.humidityPercent, weather.uvIndex,
       weather.rainChancePercent, (unsigned)weather.weatherCode);
  return true;
}

bool fetchWeather(WeatherData &weather) {
  resetWeatherData(weather);
  if (fetchWeatherOpenMeteo(weather)) return true;
  logLine("Weather fetch failed all providers");
  return false;
}

// Returns true if cached weather is still fresh
bool weatherCacheValid() {
  if (!cachedWeather.valid) return false;
  time_t now; time(&now);
  return (now - weatherFetchedAt) < WEATHER_CACHE_TTL_SEC;
}

// ---------------------------------------------------------------------------
// Thoughts
// ---------------------------------------------------------------------------

void normalizeThoughtText(const char *in, char *out, size_t outSize) {
  if (outSize == 0) return;
  size_t j = 0;
  bool prevSpace = true;
  for (size_t i = 0; in[i] != '\0' && j + 1 < outSize; ++i) {
    unsigned char c = (unsigned char)in[i];
    // Smart quotes and common Unicode punctuation -> ASCII equivalents
    if (c == 0xE2) {
      unsigned char c2 = (unsigned char)in[i+1];
      unsigned char c3 = (unsigned char)in[i+2];
      if (c2 == 0x80) {
        if (c3 == 0x98 || c3 == 0x99) { out[j++] = '\''; i += 2; prevSpace = false; continue; }
        if (c3 == 0x9C || c3 == 0x9D) { out[j++] = '"';  i += 2; prevSpace = false; continue; }
        if (c3 == 0x93 || c3 == 0x94) { out[j++] = '"';  i += 2; prevSpace = false; continue; }
        if (c3 == 0x94 || c3 == 0x95) { out[j++] = '-';  i += 2; prevSpace = false; continue; }
        if (c3 == 0xA6)               { out[j++] = '.';  out[j++] = '.'; out[j++] = '.'; i += 2; prevSpace = false; continue; }
      }
      // skip other multi-byte sequences
      if ((c2 & 0xC0) == 0x80) { i++; continue; }
      if ((c3 & 0xC0) == 0x80) { i += 2; continue; }
      continue;
    }
    char ch = (char)c;
    if (ch == '\r' || ch == '\n' || ch == '\t') ch = ' ';
    if (c < 32) continue;
    if (c > 126) continue; // drop remaining non-ASCII
    if (ch == ' ') {
      if (prevSpace) continue;
      prevSpace = true;
    } else {
      prevSpace = false;
    }
    out[j++] = ch;
  }
  while (j > 0 && out[j-1] == ' ') --j;
  out[j] = '\0';
}

void setClassicalThought(ThoughtData &thought, bool clockValid) {
  static const struct { const char *text; const char *source; } kQuotes[] = {
    {"What you seek is seeking you.",                              "Rumi"},
    {"The wound is the place where the light enters you.",         "Rumi"},
    {"Let yourself be silently drawn by what you truly love.",     "Rumi"},
    {"Raise your words, not your voice.",                          "Rumi"},
    {"Love is the bridge between you and everything.",             "Rumi"},
    {"Yesterday I was clever, so I wanted to change the world.",   "Rumi"},
    {"Knowledge without action is wastefulness.",                  "Imam al-Ghazali"},
    {"Action without knowledge is foolishness.",                   "Imam al-Ghazali"},
    {"Patience turns hardship into wisdom.",                       "Imam al-Ghazali"},
  };
  constexpr size_t kCount = sizeof(kQuotes) / sizeof(kQuotes[0]);

  uint32_t seed = bootCount;
  if (clockValid) { time_t now; time(&now); seed += (uint32_t)(now / 3600); }
  const size_t idx = seed % kCount;
  strncpy(thought.text,   kQuotes[idx].text,   sizeof(thought.text)   - 1);
  strncpy(thought.source, kQuotes[idx].source, sizeof(thought.source) - 1);
  thought.text[sizeof(thought.text)-1]     = '\0';
  thought.source[sizeof(thought.source)-1] = '\0';
  thought.valid    = true;
  thought.error[0] = '\0';
}

bool fetchShowerThought(ThoughtData &thought) {
  memset(&thought, 0, sizeof(thought));
  const String url = "https://www.reddit.com/r/Showerthoughts/top.json?t=day&limit=25";

  String payload;
  int code = 0;
  if (!httpGetRetry("Thought[Reddit]", url, payload, code)) {
    snprintf(thought.error, sizeof(thought.error), "HTTP %d", code);
    return false;
  }

  JsonDocument doc;
  if (deserializeJson(doc, payload)) {
    strncpy(thought.error, "JSON parse error", sizeof(thought.error)-1);
    return false;
  }

  JsonArray children = doc["data"]["children"];
  if (children.isNull() || children.size() == 0) {
    strncpy(thought.error, "no posts", sizeof(thought.error)-1);
    return false;
  }

  for (JsonObject child : children) {
    JsonObject post = child["data"];
    if (post.isNull()) continue;
    if ((post["stickied"] | false) || (post["over_18"] | false)) continue;
    const char *title = post["title"] | "";
    if (title[0] == '\0') continue;
    normalizeThoughtText(title, thought.text, sizeof(thought.text));
    if (strlen(thought.text) < 16) continue;
    strncpy(thought.source, "r/Showerthoughts", sizeof(thought.source)-1);
    thought.source[sizeof(thought.source)-1] = '\0';
    thought.valid    = true;
    thought.error[0] = '\0';
    return true;
  }
  strncpy(thought.error, "no suitable post", sizeof(thought.error)-1);
  return false;
}

void selectThought(ThoughtData &thought, bool wifiConnected, bool clockValid) {
  ThoughtData classical = {false,"","",""};
  setClassicalThought(classical, clockValid);

  if (!wifiConnected) { thought = classical; return; }

  ThoughtData reddit = {false,"","",""};
  const bool hasReddit = fetchShowerThought(reddit);
  if (!hasReddit) {
    thought = classical;
    strncpy(thought.error, reddit.error, sizeof(thought.error)-1);
    return;
  }
  thought = ((esp_random() & 1U) == 0U) ? reddit : classical;
}

// ---------------------------------------------------------------------------
// Market prices
// ---------------------------------------------------------------------------

void setMarketError(MarketData &market, const char *fmt, ...) {
  va_list args;
  va_start(args, fmt);
  vsnprintf(market.error, sizeof(market.error), fmt, args);
  va_end(args);
  logf("Market error: %s", market.error);
}

bool fetchMarketPrices(MarketData &market) {
  memset(&market, 0, sizeof(market));

  auto finalizeMarket = [&]() {
    market.hasZarUsd = market.zarUsd > 0.0f;
    market.hasZarMur = market.zarMur > 0.0f;
    market.valid = market.hasBtc || market.hasEth || market.hasGold || market.hasOil ||
                   market.hasZarUsd || market.hasZarMur;
  };

  // --- Yahoo Finance ---
  {
    const String url =
        "https://query1.finance.yahoo.com/v7/finance/quote?"
        "symbols=BTC-USD,ETH-USD,GC=F,CL=F,USDZAR=X,USDMUR=X";
    String payload; int code = 0;
    if (httpGetRetry("Market[Yahoo]", url, payload, code)) {
      JsonDocument doc;
      if (!deserializeJson(doc, payload)) {
        JsonArray results = doc["quoteResponse"]["result"];
        if (!results.isNull()) {
          float usdZar=0, usdMur=0; bool hasUsdZar=false, hasUsdMur=false;
          for (JsonObject q : results) {
            const char *sym = q["symbol"] | "";
            float price = q["regularMarketPrice"] | NAN;
            if (isnan(price)) continue;
            if      (strcmp(sym,"BTC-USD")==0)  { market.btcUsd=price; market.hasBtc=true; }
            else if (strcmp(sym,"ETH-USD")==0)  { market.ethUsd=price; market.hasEth=true; }
            else if (strcmp(sym,"GC=F")==0)     { market.goldUsd=price; market.hasGold=true; }
            else if (strcmp(sym,"CL=F")==0)     { market.oilUsd=price; market.hasOil=true; }
            else if (strcmp(sym,"USDZAR=X")==0) { usdZar=price; hasUsdZar=true; }
            else if (strcmp(sym,"USDMUR=X")==0) { usdMur=price; hasUsdMur=true; }
          }
          if (hasUsdZar && usdZar>0) market.zarUsd = usdZar;
          if (hasUsdZar && hasUsdMur && usdZar>0) market.zarMur = usdMur / usdZar;
        }
      }
    }
  }

  // --- Binance crypto fallback ---
  auto fetchBinanceOne = [&](const char *tag, const char *sym, float &out, bool &flag) {
    if (flag) return;
    String url = "https://api.binance.com/api/v3/ticker/price?symbol=";
    url += sym;
    String payload; int code = 0;
    if (!httpGetRetry(tag, url, payload, code)) return;
    JsonDocument doc;
    if (deserializeJson(doc, payload)) return;
    float p = (float)atof(doc["price"] | "0");
    if (p > 0) { out = p; flag = true; }
  };
  fetchBinanceOne("Market[Binance][BTC]", "BTCUSDT", market.btcUsd, market.hasBtc);
  fetchBinanceOne("Market[Binance][ETH]", "ETHUSDT", market.ethUsd, market.hasEth);

  // --- ER-API forex fallback ---
  if (!market.hasZarUsd || !market.hasZarMur) {
    String payload; int code = 0;
    if (httpGetRetry("Market[ER-API]", "https://open.er-api.com/v6/latest/USD", payload, code)) {
      JsonDocument doc;
      if (!deserializeJson(doc, payload)) {
        float usdZar = doc["rates"]["ZAR"] | 0.0f;
        float usdMur = doc["rates"]["MUR"] | 0.0f;
        if (usdZar > 0) { market.zarUsd = usdZar; market.hasZarUsd = true; }
        if (usdZar > 0 && usdMur > 0) { market.zarMur = usdMur / usdZar; market.hasZarMur = true; }
      }
    }
  }

  // --- Stooq commodities fallback ---
  auto fetchStooqOne = [&](const char *tag, const char *sym, float &out, bool &flag) {
    if (flag) return;
    String url = "https://stooq.com/q/l/?s="; url += sym; url += "&f=sd2t2ohlcv&h&e=csv";
    String payload; int code = 0;
    if (!httpGetRetry(tag, url, payload, code)) return;
    int start = 0;
    while (start < (int)payload.length()) {
      int end = payload.indexOf('\n', start);
      if (end < 0) end = payload.length();
      String line = payload.substring(start, end);
      line.trim(); start = end + 1;
      if (line.length() == 0 || line.startsWith("Symbol")) continue;
      String fields[8]; int fi = 0, p = 0;
      while (fi < 8) {
        int c = line.indexOf(',', p);
        if (c < 0) { fields[fi++] = line.substring(p); break; }
        fields[fi++] = line.substring(p, c); p = c + 1;
      }
      if (fi < 7) continue;
      float closePrice = fields[6].toFloat();
      if (closePrice <= 0) closePrice = fields[3].toFloat();
      if (closePrice > 0) { out = closePrice; flag = true; return; }
    }
  };
  fetchStooqOne("Market[Stooq][Gold]", "gc.f", market.goldUsd, market.hasGold);
  fetchStooqOne("Market[Stooq][Oil]",  "cl.f", market.oilUsd,  market.hasOil);

  finalizeMarket();
  if (market.valid) {
    market.error[0] = '\0';
    logf("Market: BTC %.2f ETH %.2f Gold %.2f Oil %.2f USDZAR %.4f ZARMUR %.4f",
         market.btcUsd, market.ethUsd, market.goldUsd, market.oilUsd,
         market.zarUsd, market.zarMur);
  } else {
    setMarketError(market, "all providers failed");
  }
  return market.valid;
}

// ---------------------------------------------------------------------------
// Prayer times
// ---------------------------------------------------------------------------

bool fetchPrayerTimes(PrayerData &prayer) {
  memset(&prayer, 0, sizeof(prayer));

  time_t now; time(&now);
  char url[256];
  snprintf(url, sizeof(url),
    "https://api.aladhan.com/v1/timings/%lld?latitude=%.4f&longitude=%.4f&method=%d",
    (long long)now, (double)WEATHER_LATITUDE, (double)WEATHER_LONGITUDE,
    PRAYER_CALC_METHOD);

  String payload; int code = 0;
  if (!httpGetRetry("Prayer[Aladhan]", String(url), payload, code)) {
    snprintf(prayer.error, sizeof(prayer.error), "HTTP %d", code);
    return false;
  }

  JsonDocument doc;
  if (deserializeJson(doc, payload)) {
    strncpy(prayer.error, "JSON parse error", sizeof(prayer.error)-1);
    return false;
  }

  JsonVariant timings = doc["data"]["timings"];
  if (timings.isNull()) {
    strncpy(prayer.error, "missing timings", sizeof(prayer.error)-1);
    return false;
  }

  auto copyTime = [](const char *src, char *dst, size_t n) {
    strncpy(dst, src, n-1); dst[n-1] = '\0';
    // Strip timezone suffix like " (SAST)" if present
    char *paren = strchr(dst, ' ');
    if (paren) *paren = '\0';
  };

  copyTime(timings["Fajr"]    | "", prayer.fajr,    sizeof(prayer.fajr));
  copyTime(timings["Dhuhr"]   | "", prayer.dhuhr,   sizeof(prayer.dhuhr));
  copyTime(timings["Asr"]     | "", prayer.asr,     sizeof(prayer.asr));
  copyTime(timings["Maghrib"] | "", prayer.maghrib, sizeof(prayer.maghrib));
  copyTime(timings["Isha"]    | "", prayer.isha,    sizeof(prayer.isha));

  struct tm timeinfo; localtime_r(&now, &timeinfo);
  strftime(prayer.date, sizeof(prayer.date), "%d %b %Y", &timeinfo);

  prayer.valid = true;
  logf("Prayer: Fajr=%s Dhuhr=%s Asr=%s Maghrib=%s Isha=%s",
       prayer.fajr, prayer.dhuhr, prayer.asr, prayer.maghrib, prayer.isha);
  return true;
}

// Returns true if cached prayer is still for today
bool prayerCacheValid() {
  if (!cachedPrayer.valid) return false;
  time_t now; time(&now);
  struct tm tm_now; localtime_r(&now, &tm_now);
  struct tm tm_fetched; localtime_r(&prayerFetchedDay, &tm_fetched);
  return (tm_now.tm_year == tm_fetched.tm_year &&
          tm_now.tm_yday == tm_fetched.tm_yday);
}

// ---------------------------------------------------------------------------
// News / HackerNews
// ---------------------------------------------------------------------------

bool fetchNewsHeadline(NewsData &news) {
  memset(&news, 0, sizeof(news));

  // HackerNews Algolia front-page search (no API key needed)
  const String url =
      "https://hn.algolia.com/api/v1/search?tags=front_page&hitsPerPage=10";

  String payload; int code = 0;
  if (!httpGetRetry("News[HN]", url, payload, code)) {
    snprintf(news.error, sizeof(news.error), "HTTP %d", code);
    return false;
  }

  JsonDocument doc;
  if (deserializeJson(doc, payload)) {
    strncpy(news.error, "JSON parse error", sizeof(news.error)-1);
    return false;
  }

  JsonArray hits = doc["hits"];
  if (hits.isNull() || hits.size() == 0) {
    strncpy(news.error, "no hits", sizeof(news.error)-1);
    return false;
  }

  // Pick first hit with a non-empty title
  for (JsonObject hit : hits) {
    const char *title = hit["title"] | "";
    if (title[0] == '\0') continue;
    normalizeThoughtText(title, news.headline, sizeof(news.headline));
    if (strlen(news.headline) < 8) continue;

    int points = hit["points"] | 0;
    if (points >= 1000) {
      snprintf(news.score, sizeof(news.score), "%.1fk pts", points / 1000.0f);
    } else {
      snprintf(news.score, sizeof(news.score), "%d pts", points);
    }

    // Extract domain from url for attribution
    const char *storyUrl = hit["url"] | "";
    strncpy(news.source, "Hacker News", sizeof(news.source)-1);
    if (storyUrl[0] != '\0') {
      // Find domain: skip https://  then take until next /
      const char *domStart = strstr(storyUrl, "://");
      if (domStart) {
        domStart += 3;
        const char *domEnd = strchr(domStart, '/');
        size_t len = domEnd ? (size_t)(domEnd - domStart) : strlen(domStart);
        // Skip www.
        if (strncmp(domStart, "www.", 4) == 0) { domStart += 4; len -= 4; }
        if (len > 0 && len < sizeof(news.source)-1) {
          strncpy(news.source, domStart, len);
          news.source[len] = '\0';
        }
      }
    }

    news.valid    = true;
    news.error[0] = '\0';
    logf("News: '%s' (%s, %s)", news.headline, news.source, news.score);
    return true;
  }

  strncpy(news.error, "no suitable story", sizeof(news.error)-1);
  return false;
}

// ---------------------------------------------------------------------------
// Moon phase
// ---------------------------------------------------------------------------

// Returns 0-7: 0=New, 1=WaxCrescent, 2=FirstQuarter, 3=WaxGibbous,
//              4=Full, 5=WanGibbous, 6=LastQuarter, 7=WanCrescent
uint8_t moonPhaseIndex(time_t t) {
  // Known new moon: Jan 6 2000 18:14 UTC = 947182440
  const double knownNewMoon = 947182440.0;
  const double synodicMonth = 29.53058867;
  double daysSince = (t - knownNewMoon) / 86400.0;
  double cycles = daysSince / synodicMonth;
  double phase = cycles - (long long)cycles; // fractional part [0,1)
  if (phase < 0) phase += 1.0;
  return (uint8_t)(phase * 8.0) % 8;
}

const char *moonPhaseName(uint8_t phase) {
  static const char *names[] = {
    "New", "Wax Crescent", "1st Qtr", "Wax Gibbous",
    "Full", "Wan Gibbous", "Last Qtr", "Wan Crescent"
  };
  return names[phase % 8];
}

void drawMoonPhase(int16_t cx, int16_t cy, uint8_t phase) {
  const int16_t r = 6;
  display.drawCircle(cx, cy, r, GxEPD_BLACK);
  switch (phase) {
    case 0: // New - empty circle (already drawn)
      break;
    case 4: // Full - filled
      display.fillCircle(cx, cy, r, GxEPD_BLACK);
      break;
    case 2: // First quarter - right half filled
      display.fillRect(cx, cy - r, r + 1, r * 2 + 1, GxEPD_BLACK);
      display.drawCircle(cx, cy, r, GxEPD_BLACK);
      break;
    case 6: // Last quarter - left half filled
      display.fillRect(cx - r, cy - r, r + 1, r * 2 + 1, GxEPD_BLACK);
      display.drawCircle(cx, cy, r, GxEPD_BLACK);
      break;
    case 1: // Waxing crescent - thin right sliver
      display.fillRect(cx + r/2, cy - r, r - r/2 + 1, r * 2 + 1, GxEPD_BLACK);
      display.drawCircle(cx, cy, r, GxEPD_BLACK);
      break;
    case 3: // Waxing gibbous - mostly right filled
      display.fillRect(cx - r/3, cy - r, r + r/3 + 1, r * 2 + 1, GxEPD_BLACK);
      display.drawCircle(cx, cy, r, GxEPD_BLACK);
      break;
    case 5: // Waning gibbous - mostly left filled
      display.fillRect(cx - r, cy - r, r + r/3 + 1, r * 2 + 1, GxEPD_BLACK);
      display.drawCircle(cx, cy, r, GxEPD_BLACK);
      break;
    case 7: // Waning crescent - thin left sliver
      display.fillRect(cx - r, cy - r, r - r/2 + 1, r * 2 + 1, GxEPD_BLACK);
      display.drawCircle(cx, cy, r, GxEPD_BLACK);
      break;
  }
}

// ---------------------------------------------------------------------------
// Weather icons
// ---------------------------------------------------------------------------

enum class WeatherIcon : uint8_t { Sun, Cloud, Rain, Storm, Snow, Fog, Unknown };

WeatherIcon iconFromWeatherCode(uint16_t code) {
  if (code <= 99) {
    if (code == 0)                                          return WeatherIcon::Sun;
    if (code <= 3)                                          return WeatherIcon::Cloud;
    if (code == 45 || code == 48)                           return WeatherIcon::Fog;
    if (code == 95 || code == 96 || code == 99)             return WeatherIcon::Storm;
    if (code==71||code==73||code==75||code==77||code==85||code==86) return WeatherIcon::Snow;
    if (code>=51&&code<=82)                                 return WeatherIcon::Rain;
    return WeatherIcon::Unknown;
  }
  if (code == 800)                    return WeatherIcon::Sun;
  if (code >= 801 && code <= 804)     return WeatherIcon::Cloud;
  if (code >= 701 && code <= 781)     return WeatherIcon::Fog;
  if (code >= 200 && code <= 232)     return WeatherIcon::Storm;
  if (code >= 600 && code <= 622)     return WeatherIcon::Snow;
  if (code >= 300 && code <= 531)     return WeatherIcon::Rain;
  return WeatherIcon::Unknown;
}

void drawSunIcon(int16_t x, int16_t y) {
  static const int8_t rays[8][2] = {{0,-5},{4,-4},{5,0},{4,4},{0,5},{-4,4},{-5,0},{-4,-4}};
  const int16_t cx = x+10, cy = y+9;
  display.drawCircle(cx, cy, 4, GxEPD_BLACK);
  display.fillCircle(cx, cy, 2, GxEPD_BLACK);
  for (uint8_t i=0; i<8; ++i)
    display.drawLine(cx+rays[i][0], cy+rays[i][1],
                     cx+(rays[i][0]*7)/5, cy+(rays[i][1]*7)/5, GxEPD_BLACK);
}

void drawCloudBase(int16_t x, int16_t y) {
  display.drawCircle(x+6,  y+10, 4, GxEPD_BLACK);
  display.drawCircle(x+11, y+8,  5, GxEPD_BLACK);
  display.drawCircle(x+16, y+10, 4, GxEPD_BLACK);
  display.drawRoundRect(x+4, y+10, 14, 6, 2, GxEPD_BLACK);
}

void drawRainIcon(int16_t x, int16_t y) {
  drawCloudBase(x, y);
  display.drawLine(x+7,  y+15, x+5,  y+18, GxEPD_BLACK);
  display.drawLine(x+11, y+15, x+9,  y+18, GxEPD_BLACK);
  display.drawLine(x+15, y+15, x+13, y+18, GxEPD_BLACK);
}

void drawStormIcon(int16_t x, int16_t y) {
  drawCloudBase(x, y);
  display.drawLine(x+10, y+14, x+8,  y+18, GxEPD_BLACK);
  display.drawLine(x+8,  y+18, x+12, y+18, GxEPD_BLACK);
  display.drawLine(x+12, y+18, x+10, y+22, GxEPD_BLACK);
}

void drawSnowIcon(int16_t x, int16_t y) {
  drawCloudBase(x, y);
  display.drawLine(x+8,  y+16, x+8,  y+20, GxEPD_BLACK);
  display.drawLine(x+6,  y+18, x+10, y+18, GxEPD_BLACK);
  display.drawLine(x+14, y+16, x+14, y+20, GxEPD_BLACK);
  display.drawLine(x+12, y+18, x+16, y+18, GxEPD_BLACK);
}

void drawFogIcon(int16_t x, int16_t y) {
  drawCloudBase(x, y-2);
  display.drawLine(x+4,  y+14, x+18, y+14, GxEPD_BLACK);
  display.drawLine(x+3,  y+17, x+17, y+17, GxEPD_BLACK);
}

void drawUnknownIcon(int16_t x, int16_t y) {
  display.drawCircle(x+11, y+10, 7, GxEPD_BLACK);
  display.drawLine(x+8, y+7, x+14, y+13, GxEPD_BLACK);
  display.drawLine(x+14, y+7, x+8, y+13, GxEPD_BLACK);
}

void drawWeatherIconAt(int16_t x, int16_t y, const WeatherData &weather) {
  if (!weather.valid) { drawUnknownIcon(x, y); return; }
  switch (iconFromWeatherCode(weather.weatherCode)) {
    case WeatherIcon::Sun:   drawSunIcon(x, y);   break;
    case WeatherIcon::Cloud: drawCloudBase(x, y); break;
    case WeatherIcon::Rain:  drawRainIcon(x, y);  break;
    case WeatherIcon::Storm: drawStormIcon(x, y); break;
    case WeatherIcon::Snow:  drawSnowIcon(x, y);  break;
    case WeatherIcon::Fog:   drawFogIcon(x, y);   break;
    default:                 drawUnknownIcon(x, y); break;
  }
}

// Small weather corner widget: tiny icon (scaled to ~12px) + temperature
// Positioned so time "HH:MM" fits at x=228 and icon cluster left of that
void drawWeatherCorner(const WeatherData &w) {
  if (!w.valid) return;
  // Temperature sits right after the time (HH:MM = ~60px from X=4, so start at X=70)
  char buf[12];
  snprintf(buf, sizeof(buf), "%.0fC", w.temperatureC);
  display.setFont(&FreeMono9pt7b);
  display.setCursor(70, 14);
  display.print(buf);
}

void drawMarketIcon() {
  const int16_t x=273, y=2;
  display.drawRect(x+1, y+2, 20, 13, GxEPD_BLACK);
  display.drawLine(x+3,  y+12, x+8,  y+9,  GxEPD_BLACK);
  display.drawLine(x+8,  y+9,  x+12, y+10, GxEPD_BLACK);
  display.drawLine(x+12, y+10, x+17, y+6,  GxEPD_BLACK);
  display.drawLine(x+17, y+6,  x+19, y+7,  GxEPD_BLACK);
}

// ---------------------------------------------------------------------------
// Header helpers
// ---------------------------------------------------------------------------

void drawHeaderBase(const char *title) {
  display.setFont(&FreeMono9pt7b);
  display.setTextColor(GxEPD_BLACK);
  // Title starts at X=112 to leave room for time+temp on the left
  display.setCursor(112, 14);
  display.print(title);
  display.drawLine(0, 18, 295, 18, GxEPD_BLACK);
}

// Draws only the HH:MM clock in the header row (call after drawHeaderBase)
// Time is now on the far left (X=4)
void drawHeaderClock(bool clockValid) {
  if (!clockValid) return;
  char timeBuf[8];
  time_t now; time(&now);
  struct tm timeinfo; localtime_r(&now, &timeinfo);
  strftime(timeBuf, sizeof(timeBuf), "%H:%M", &timeinfo);
  display.setFont(&FreeMono9pt7b);
  display.setCursor(4, 14);
  display.print(timeBuf);
}

// ---------------------------------------------------------------------------
// Text wrap helper
// ---------------------------------------------------------------------------

void drawWrappedLineBlock(const char *text, int16_t x, int16_t y,
                          int16_t maxWidth, uint8_t maxLines, int16_t lineHeight) {
  String line = "", word = "";
  uint8_t linesUsed = 0;

  auto lineWidth = [](const String &s) -> uint16_t {
    int16_t x1, y1; uint16_t w, h;
    display.getTextBounds(s, 0, 0, &x1, &y1, &w, &h);
    return w;
  };

  auto flushLine = [&](const String &toPrint) -> bool {
    if (linesUsed >= maxLines) return false;
    display.setCursor(x, y + (int16_t)(linesUsed * lineHeight));
    display.print(toPrint);
    return ++linesUsed < maxLines;
  };

  const size_t len = strlen(text);
  for (size_t i = 0; i <= len; ++i) {
    const char c = (i < len) ? text[i] : ' ';
    const bool isBreak = (c==' ' || c=='\n' || i==len);
    if (!isBreak) { word += c; continue; }
    if (word.length() > 0) {
      String candidate = line.length() > 0 ? line + " " + word : word;
      if (lineWidth(candidate) <= (uint16_t)maxWidth) {
        line = candidate;
      } else {
        if (line.length() > 0) {
          if (!flushLine(line)) return;
          line = word;
        } else {
          String chunk = "";
          for (size_t j = 0; j < word.length(); ++j) {
            String test = chunk + word[j];
            if (lineWidth(test) <= (uint16_t)maxWidth) { chunk = test; }
            else { if (!flushLine(chunk)) return; chunk = String(word[j]); }
          }
          line = chunk;
        }
      }
      word = "";
    }
    if (c == '\n' && line.length() > 0) {
      if (!flushLine(line)) return;
      line = "";
    }
  }
  if (line.length() > 0 && linesUsed < maxLines) flushLine(line);
}

// ---------------------------------------------------------------------------
// Screen: Clock + Weather
// ---------------------------------------------------------------------------

void drawClockWeatherScreen(const WeatherData &weather, bool clockValid,
                            bool wifiConnected) {
  logf("Render weather screen. clockValid=%d weatherValid=%d", clockValid, weather.valid);
  display.setRotation(1);
  display.setFullWindow();

  char timeBuf[12]  = "--:--";
  char dateBuf[24]  = "No time sync";

  if (clockValid) {
    time_t now; time(&now);
    struct tm timeinfo; localtime_r(&now, &timeinfo);
    strftime(timeBuf, sizeof(timeBuf), "%H:%M", &timeinfo);
    strftime(dateBuf, sizeof(dateBuf), "%a %b %d", &timeinfo);
  }

  // Moon phase
  uint8_t moonPhase = 0;
  bool showMoon = false;
  if (clockValid) {
    time_t now; time(&now);
    moonPhase = moonPhaseIndex(now);
    showMoon = true;
  }

  display.firstPage();
  do {
    display.fillScreen(GxEPD_WHITE);
    drawHeaderBase("Clock + Weather");
    drawWeatherIconAt(273, 0, weather);

    display.setFont(&FreeMonoBold18pt7b);
    display.setCursor(8, 62);
    display.print(timeBuf);

    display.setFont(&FreeMono9pt7b);
    display.setCursor(8, 86);
    display.print(dateBuf);

    if (weather.valid) {
      display.setCursor(8, 102);
      display.printf("Temp %.1fC Feels %.1fC", weather.temperatureC,
                     weather.apparentTemperatureC);
      display.setCursor(8, 118);
      display.printf("Hum %.0f%% UV ", weather.humidityPercent);
      if (weather.uvIndex >= 0) display.print(weather.uvIndex, 1);
      else display.print("n/a");
      display.print(" Rain ");
      if (weather.rainChancePercent >= 0) {
        display.print(weather.rainChancePercent); display.print("%");
      } else {
        display.print("n/a");
      }
    } else {
      display.setCursor(8, 108);
      display.print("Weather unavailable");
      display.setCursor(8, 126);
      display.print(wifiConnected ? "API error" : "Wi-Fi disconnected");
    }

    // Moon phase in bottom-right
    if (showMoon) {
      drawMoonPhase(280, 110, moonPhase);
      display.setFont(&FreeMono9pt7b);
      // no text label — icon is self-explanatory
    }
  } while (display.nextPage());
}

// ---------------------------------------------------------------------------
// Screen: Market prices
// ---------------------------------------------------------------------------

void drawMarketScreen(const MarketData &market, bool clockValid,
                      bool wifiConnected, const WeatherData &weather) {
  logf("Render market screen. clockValid=%d marketValid=%d", clockValid, market.valid);
  display.setRotation(1);
  display.setFullWindow();

  auto drawTrendSuffix = [](bool hasCur, float cur, bool hasPrev, float prev, float thr) {
    if (!hasCur || !hasPrev) return;
    float delta = cur - prev;
    char trend = (delta > thr) ? '^' : (delta < -thr) ? 'v' : '=';
    display.print(" "); display.print(trend);
  };

  const bool hasPrev = lastMarketData.valid;
  display.firstPage();
  do {
    display.fillScreen(GxEPD_WHITE);
    drawHeaderBase("Markets (USD)");
    drawMarketIcon();
    display.setFont(&FreeMono9pt7b);
    drawHeaderClock(clockValid); // just prints time, title already drawn
    drawWeatherCorner(weather);

    if (market.valid) {
      display.setCursor(8, 36);
      if (market.hasBtc) {
        display.printf("BTC : $%.2f", market.btcUsd);
        drawTrendSuffix(market.hasBtc, market.btcUsd, lastMarketData.hasBtc, lastMarketData.btcUsd, 0.005f);
      } else display.print("BTC : n/a");

      display.setCursor(8, 50);
      if (market.hasEth) {
        display.printf("ETH : $%.2f", market.ethUsd);
        drawTrendSuffix(market.hasEth, market.ethUsd, lastMarketData.hasEth, lastMarketData.ethUsd, 0.005f);
      } else display.print("ETH : n/a");

      display.setCursor(8, 64);
      if (market.hasGold) {
        display.printf("Gold: $%.2f", market.goldUsd);
        drawTrendSuffix(market.hasGold, market.goldUsd, lastMarketData.hasGold, lastMarketData.goldUsd, 0.005f);
      } else display.print("Gold: n/a");

      display.setCursor(8, 78);
      if (market.hasOil) {
        display.printf("Oil : $%.2f", market.oilUsd);
        drawTrendSuffix(market.hasOil, market.oilUsd, lastMarketData.hasOil, lastMarketData.oilUsd, 0.005f);
      } else display.print("Oil : n/a");

      display.setCursor(8, 92);
      if (market.hasZarUsd) {
        display.printf("USD/ZAR: %.5f", market.zarUsd);
        drawTrendSuffix(market.hasZarUsd, market.zarUsd, lastMarketData.hasZarUsd, lastMarketData.zarUsd, 0.000005f);
      } else display.print("USD/ZAR: n/a");

      display.setCursor(8, 106);
      if (market.hasZarMur) {
        display.printf("ZAR/MUR: %.5f", market.zarMur);
        drawTrendSuffix(market.hasZarMur, market.zarMur, lastMarketData.hasZarMur, lastMarketData.zarMur, 0.000005f);
      } else display.print("ZAR/MUR: n/a");
    } else {
      display.setCursor(8, 72);
      display.print("Market data unavailable");
      display.setCursor(8, 94);
      if (!wifiConnected) display.print("Wi-Fi disconnected");
      else if (market.error[0] != '\0') display.print(market.error);
      else display.print("API error");
    }
  } while (display.nextPage());

  if (market.valid) {
    lastMarketData = market;
    lastMarketData.error[0] = '\0';
  }
}

// ---------------------------------------------------------------------------
// Screen: Thoughts
// ---------------------------------------------------------------------------

void drawThoughtScreen(const ThoughtData &thought, bool clockValid,
                       bool wifiConnected, const WeatherData &weather) {
  logf("Render thought screen. thoughtValid=%d", thought.valid);
  display.setRotation(1);
  display.setFullWindow();

  display.firstPage();
  do {
    display.fillScreen(GxEPD_WHITE);
    drawHeaderBase("Shower Thoughts");
    // Thought bubble icon
    const int16_t ix=273, iy=2;
    display.drawRoundRect(ix+1, iy+2, 20, 13, 2, GxEPD_BLACK);
    display.fillRect(ix+5, iy+6, 2, 4, GxEPD_BLACK);
    display.fillRect(ix+9, iy+6, 2, 4, GxEPD_BLACK);

    display.setFont(&FreeMono9pt7b);
    drawHeaderClock(clockValid);
    drawWeatherCorner(weather);

    if (thought.valid) {
      drawWrappedLineBlock(thought.text, 8, 44, 280, 6, 14);
      display.setCursor(8, 122);
      display.print("- ");
      display.print(thought.source[0] ? thought.source : "Thought");
    } else {
      display.setCursor(8, 72);
      display.print("Thought unavailable");
      display.setCursor(8, 94);
      display.print(wifiConnected ? thought.error : "Wi-Fi disconnected");
    }
  } while (display.nextPage());
}

// ---------------------------------------------------------------------------
// Screen: Focus
// ---------------------------------------------------------------------------

void drawFocusScreen(bool clockValid, const WeatherData &weather) {
  logf("Render focus screen. clockValid=%d", clockValid);
  display.setRotation(1);
  display.setFullWindow();

  char weekBuf[16] = "";
  char dateBuf[24] = "";

  if (clockValid) {
    time_t now; time(&now);
    struct tm timeinfo; localtime_r(&now, &timeinfo);
    strftime(dateBuf, sizeof(dateBuf), "%a %b %d", &timeinfo);
    char wBuf[4]; strftime(wBuf, sizeof(wBuf), "%V", &timeinfo);
    snprintf(weekBuf, sizeof(weekBuf), "Wk %s", wBuf);
  }

  display.firstPage();
  do {
    display.fillScreen(GxEPD_WHITE);
    drawHeaderBase("Focus");
    display.setFont(&FreeMono9pt7b);
    drawHeaderClock(clockValid);
    drawWeatherCorner(weather);

    // Large focus word centered
    display.setFont(&FreeMonoBold18pt7b);
    {
      int16_t x1, y1; uint16_t w, h;
      display.getTextBounds(FOCUS_WORD, 0, 0, &x1, &y1, &w, &h);
      int16_t cx = (296 - (int16_t)w) / 2;
      display.setCursor(cx < 0 ? 0 : cx, 75);
    }
    display.print(FOCUS_WORD);

    display.setFont(&FreeMono9pt7b);
    display.setCursor(8, 104);
    display.print(weekBuf);
    display.print("  ");
    display.print(dateBuf);
  } while (display.nextPage());
}

// ---------------------------------------------------------------------------
// Screen: Prayer times
// ---------------------------------------------------------------------------

// Parse "HH:MM" into minutes-since-midnight, returns -1 on failure
static int prayerTimeToMinutes(const char *t) {
  if (!t || strlen(t) < 5) return -1;
  int h = (t[0]-'0')*10 + (t[1]-'0');
  int m = (t[3]-'0')*10 + (t[4]-'0');
  return h * 60 + m;
}

void drawPrayerScreen(const PrayerData &prayer, bool clockValid,
                      bool wifiConnected, const WeatherData &weather) {
  logf("Render prayer screen. prayerValid=%d", prayer.valid);
  display.setRotation(1);
  display.setFullWindow();

  // Determine current prayer slot to highlight
  int nowMinutes = -1;
  if (clockValid) {
    time_t now; time(&now);
    struct tm timeinfo; localtime_r(&now, &timeinfo);
    nowMinutes = timeinfo.tm_hour * 60 + timeinfo.tm_min;
  }

  // Find next prayer: first whose time > nowMinutes
  const char *prayerNames[5]  = {"Fajr", "Dhuhr", "Asr", "Maghrib", "Isha"};
  const char *prayerTimes[5]  = {
    prayer.fajr, prayer.dhuhr, prayer.asr, prayer.maghrib, prayer.isha
  };
  int nextPrayer = -1;
  if (prayer.valid && nowMinutes >= 0) {
    for (int i = 0; i < 5; ++i) {
      int pm = prayerTimeToMinutes(prayerTimes[i]);
      if (pm > nowMinutes) { nextPrayer = i; break; }
    }
    // after Isha, next is Fajr tomorrow
  }

  display.firstPage();
  do {
    display.fillScreen(GxEPD_WHITE);
    drawHeaderBase("Prayer Times");
    display.setFont(&FreeMono9pt7b);
    drawHeaderClock(clockValid);
    drawWeatherCorner(weather);

    if (prayer.valid) {
      // Prayer symbol (crescent) at top right
      const int16_t cx=284, cy=9;
      display.drawCircle(cx, cy, 7, GxEPD_BLACK);
      display.fillCircle(cx+3, cy-2, 5, GxEPD_WHITE); // carve crescent

      display.setFont(&FreeMono9pt7b);
      for (int i = 0; i < 5; ++i) {
        int16_t rowY = 36 + i * 18;
        display.setCursor(8, rowY);
        if (i == nextPrayer) display.print(">");
        else                  display.print(" ");
        display.printf(" %-7s %s", prayerNames[i], prayerTimes[i]);
      }

      // Date in footer
      display.setCursor(8, 122);
      display.print(prayer.date);
    } else {
      display.setCursor(8, 72);
      display.print("Prayer times unavailable");
      display.setCursor(8, 94);
      if (!wifiConnected) display.print("Wi-Fi disconnected");
      else                display.print(prayer.error);
    }
  } while (display.nextPage());
}

// ---------------------------------------------------------------------------
// Screen: News
// ---------------------------------------------------------------------------

void drawNewsScreen(const NewsData &news, bool clockValid,
                    bool wifiConnected, const WeatherData &weather) {
  logf("Render news screen. newsValid=%d", news.valid);
  display.setRotation(1);
  display.setFullWindow();

  display.firstPage();
  do {
    display.fillScreen(GxEPD_WHITE);
    drawHeaderBase("Top News");
    display.setFont(&FreeMono9pt7b);
    drawHeaderClock(clockValid);
    drawWeatherCorner(weather);

    if (news.valid) {
      drawWrappedLineBlock(news.headline, 8, 44, 280, 5, 14);
      display.setCursor(8, 120);
      display.print("- ");
      display.print(news.source);
      if (news.score[0]) {
        display.print(" | ");
        display.print(news.score);
      }
    } else {
      display.setCursor(8, 72);
      display.print("News unavailable");
      display.setCursor(8, 94);
      if (!wifiConnected) display.print("Wi-Fi disconnected");
      else                display.print(news.error);
    }
  } while (display.nextPage());
}

// ---------------------------------------------------------------------------
// Main cycle runner
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// OTA firmware update
// ---------------------------------------------------------------------------

void drawOtaScreen(const char *line1, const char *line2 = nullptr) {
  display.setRotation(1);
  display.setFullWindow();
  display.firstPage();
  do {
    display.fillScreen(GxEPD_WHITE);
    drawHeaderBase("Firmware Update");
    display.setFont(&FreeMono9pt7b);
    display.setCursor(8, 50);
    display.print(line1);
    if (line2 && line2[0] != '\0') {
      display.setCursor(8, 70);
      display.print(line2);
    }
    display.setCursor(8, 112);
    display.print("Do not power off");
  } while (display.nextPage());
}

// Returns the optional GitHub token from config (nullptr if not set)
static const char *otaAuthToken() {
#ifdef OTA_GITHUB_TOKEN
  return OTA_GITHUB_TOKEN;
#else
  return nullptr;
#endif
}

bool fetchOtaVersionInfo(char *remoteSha, size_t shaSize, char *binaryUrl, size_t urlSize) {
  // version.json lives in the repo branch, served via raw.githubusercontent.com
  char url[256];
  snprintf(url, sizeof(url),
    "https://raw.githubusercontent.com/%s/%s/%s/version.json",
    OTA_REPO_OWNER, OTA_REPO_NAME, OTA_BRANCH);

  String payload; int code = 0;
  if (!httpGetRetry("OTA[version]", String(url), payload, code, 2, otaAuthToken())) {
    logf("OTA: version fetch failed (HTTP %d)", code);
    return false;
  }

  JsonDocument doc;
  if (deserializeJson(doc, payload)) {
    logLine("OTA: version.json parse error");
    return false;
  }

  const char *sha = doc["sha"] | "";
  const char *dlUrl = doc["url"] | "";

  if (sha[0] == '\0' || strcmp(sha, "none") == 0) {
    logLine("OTA: version.json has no valid SHA yet (CI not run?)");
    return false;
  }

  strncpy(remoteSha, sha,   shaSize  - 1); remoteSha[shaSize  - 1] = '\0';
  strncpy(binaryUrl, dlUrl, urlSize  - 1); binaryUrl[urlSize  - 1] = '\0';

  logf("OTA: remote SHA=%s url=%s", remoteSha, binaryUrl);
  return true;
}

bool streamOtaDownload(const char *binaryUrl) {
  logf("OTA: downloading from %s", binaryUrl);

  WiFiClientSecure client;
  client.setInsecure();
  HTTPClient http;
  http.setTimeout(HTTP_TIMEOUT_MS * 5); // firmware downloads take longer
  http.setFollowRedirects(HTTPC_FORCE_FOLLOW_REDIRECTS);
  if (!http.begin(client, binaryUrl)) {
    logLine("OTA: http.begin() failed for binary");
    return false;
  }
  http.addHeader("User-Agent", "EpaperDashboard/2.0");
  const char *tok = otaAuthToken();
  if (tok && tok[0] != '\0') {
    http.addHeader("Authorization", String("Bearer ") + tok);
  }
  // GitHub releases redirect to S3; the Accept header helps with API assets
  http.addHeader("Accept", "application/octet-stream");

  const int code = http.GET();
  if (code != HTTP_CODE_OK) {
    logf("OTA: binary download HTTP %d", code);
    http.end();
    return false;
  }

  const int contentLength = http.getSize();
  logf("OTA: binary size %d bytes", contentLength);

  if (!Update.begin(contentLength > 0 ? (size_t)contentLength : UPDATE_SIZE_UNKNOWN)) {
    logf("OTA: Update.begin failed. Free sketch space: %u", ESP.getFreeSketchSpace());
    http.end();
    Update.abort();
    return false;
  }

  WiFiClient *stream = http.getStreamPtr();
  uint8_t buf[512];
  size_t totalWritten = 0;
  uint32_t lastLog = millis();

  while (http.connected()) {
    size_t avail = stream->available();
    if (!avail) {
      if (contentLength > 0 && totalWritten >= (size_t)contentLength) break;
      delay(1);
      continue;
    }
    size_t toRead = min(avail, sizeof(buf));
    int n = stream->readBytes(buf, toRead);
    if (n > 0) {
      Update.write(buf, (size_t)n);
      totalWritten += (size_t)n;
    }
    if (millis() - lastLog > 3000) {
      logf("OTA: %u / %d bytes", (unsigned)totalWritten, contentLength);
      lastLog = millis();
    }
  }
  http.end();

  if (!Update.end()) {
    logf("OTA: Update.end() error: %s", Update.errorString());
    return false;
  }
  if (!Update.isFinished()) {
    logLine("OTA: Update.isFinished() false");
    return false;
  }

  logf("OTA: download complete, %u bytes written", (unsigned)totalWritten);
  return true;
}

// Returns true only if an OTA check is due.
// Checks on cold power-on boot and when midnight has been crossed since
// the last check, but never more often than OTA_CHECK_COOLDOWN_SEC.
bool shouldCheckForOta() {
  // Always check on cold boot (fresh power-on, not wake from deep sleep)
  const esp_sleep_wakeup_cause_t cause = esp_sleep_get_wakeup_cause();
  const bool isColdBoot = (cause == ESP_SLEEP_WAKEUP_UNDEFINED);

  time_t now; time(&now);
  if (!hasValidTime()) {
    // Without a valid clock we can still do the cold-boot check
    return isColdBoot && (lastOtaCheckTime == 0);
  }

  // Rate limit: never re-check within the cooldown window
  if (now - lastOtaCheckTime < OTA_CHECK_COOLDOWN_SEC) {
    return false;
  }

  if (isColdBoot) return true;

  // Midnight crossing: different calendar day since last check
  if (lastOtaCheckTime > 0) {
    struct tm tmNow;  localtime_r(&now,              &tmNow);
    struct tm tmLast; localtime_r(&lastOtaCheckTime, &tmLast);
    if (tmNow.tm_yday != tmLast.tm_yday || tmNow.tm_year != tmLast.tm_year) {
      return true;
    }
  } else {
    return true; // never checked before
  }

  return false;
}

void checkForFirmwareUpdate() {
  logLine("OTA: checking for update");

  char remoteSha[48]  = "";
  char binaryUrl[256] = "";

  if (!fetchOtaVersionInfo(remoteSha, sizeof(remoteSha), binaryUrl, sizeof(binaryUrl))) {
    logLine("OTA: could not fetch version info, skipping");
    // Still update the check timestamp so we don't hammer on every boot
    if (hasValidTime()) { time_t now; time(&now); lastOtaCheckTime = now; }
    return;
  }

  logf("OTA: local=%s remote=%s", FIRMWARE_SHA, remoteSha);

  if (strcmp(FIRMWARE_SHA, remoteSha) == 0) {
    logLine("OTA: firmware is up to date");
    if (hasValidTime()) { time_t now; time(&now); lastOtaCheckTime = now; }
    return;
  }

  if (binaryUrl[0] == '\0') {
    logLine("OTA: update available but no binary URL, skipping");
    if (hasValidTime()) { time_t now; time(&now); lastOtaCheckTime = now; }
    return;
  }

  // Show update screen BEFORE the long download
  char shaLine[64];
  snprintf(shaLine, sizeof(shaLine), "%s -> %s", FIRMWARE_SHA, remoteSha);
  drawOtaScreen("Downloading update...", shaLine);

  logf("OTA: starting download: %s", binaryUrl);
  const bool ok = streamOtaDownload(binaryUrl);

  if (ok) {
    logLine("OTA: success — restarting");
    drawOtaScreen("Update complete!", "Restarting...");
    // Reset screen list so buildScreenList() re-runs with new firmware's config
    screenCount = 0;
    delay(2000);
    esp_restart();
  } else {
    logLine("OTA: download/flash failed, continuing normal operation");
    drawOtaScreen("Update failed", "Continuing...");
    delay(2000);
    // Mark checked so we don't retry on every subsequent wake
    if (hasValidTime()) { time_t now; time(&now); lastOtaCheckTime = now; }
  }
}

// ---------------------------------------------------------------------------
// Main dashboard cycle
// ---------------------------------------------------------------------------

void runDashboardCycle(uint8_t screenId) {
  bool wifiConnected = false;
  bool clockValid    = false;

  WeatherData weather  = cachedWeather; // start with cached
  MarketData  market   = {false,false,false,false,false,false,false,0,0,0,0,0,0,""};
  ThoughtData thought  = {false,"","",""};
  PrayerData  prayer   = cachedPrayer;
  NewsData    news     = cachedNews;

  wifiConnected = connectWiFi();
  if (wifiConnected) {
    syncClock();
    clockValid = hasValidTime();

    // OTA check: runs on cold boot and midnight crossings.
    // If an update is found and flashed, esp_restart() is called inside
    // and this function never returns.
    if (shouldCheckForOta()) {
      checkForFirmwareUpdate();
    }

    // Fetch weather only if needed for this screen or cache is stale
    if (screenId == SCREEN_WEATHER || !weatherCacheValid()) {
      if (fetchWeather(weather)) {
        cachedWeather = weather;
        time_t now; time(&now); weatherFetchedAt = now;
      }
    }

    if (screenId == SCREEN_MARKET) {
      fetchMarketPrices(market);
    }
    if (screenId == SCREEN_THOUGHT) {
      selectThought(thought, true, clockValid);
    }
    if (screenId == SCREEN_PRAYER) {
      if (!prayerCacheValid()) {
        if (fetchPrayerTimes(prayer)) {
          cachedPrayer = prayer;
          time_t now; time(&now); prayerFetchedDay = now;
        }
      }
    }
    if (screenId == SCREEN_NEWS) {
      // Re-fetch news each time (headlines change frequently)
      if (fetchNewsHeadline(news)) {
        cachedNews = news;
      } else if (cachedNews.valid) {
        news = cachedNews; // use stale cache
      }
    }
  } else {
    // No Wi-Fi: use caches, fallback classical thought
    if (screenId == SCREEN_THOUGHT) {
      selectThought(thought, false, clockValid);
    }
  }

  const WeatherData &cornerWeather = cachedWeather;

  switch (screenId) {
    case SCREEN_WEATHER:
      drawClockWeatherScreen(weather, clockValid, wifiConnected);
      break;
    case SCREEN_MARKET:
      drawMarketScreen(market, clockValid, wifiConnected, cornerWeather);
      break;
    case SCREEN_THOUGHT:
      drawThoughtScreen(thought, clockValid, wifiConnected, cornerWeather);
      break;
    case SCREEN_FOCUS:
      drawFocusScreen(clockValid, cornerWeather);
      break;
    case SCREEN_PRAYER:
      drawPrayerScreen(prayer, clockValid, wifiConnected, cornerWeather);
      break;
    case SCREEN_NEWS:
      drawNewsScreen(news, clockValid, wifiConnected, cornerWeather);
      break;
    default:
      drawClockWeatherScreen(weather, clockValid, wifiConnected);
      break;
  }

  logf("Display updated for screenId=%u", (unsigned)screenId);
}

// ---------------------------------------------------------------------------
// Hardware setup + sleep
// ---------------------------------------------------------------------------

void setupDisplay() {
  logLine("Display init start");
  SPI.begin(EPD_SCK, -1, EPD_MOSI, EPD_CS);
  display.epd2.selectSPI(SPI, SPISettings(4000000, MSBFIRST, SPI_MODE0));
  display.init(115200, true, 2, false);
  logLine("Display init done");
}

void deepSleepUntilNextUpdate(uint32_t seconds) {
  logf("Deep sleep %u sec", (unsigned)seconds);
  setRgbLed(0, 0, 0);
  display.hibernate();
  WiFi.disconnect(true, true);
  WiFi.mode(WIFI_OFF);
  esp_sleep_enable_timer_wakeup((uint64_t)seconds * 1000000ULL);
  Serial.flush(); Serial0.flush();
  esp_deep_sleep_start();
}

// ---------------------------------------------------------------------------
// Arduino entry points
// ---------------------------------------------------------------------------

void setup() {
  // Build screen list on first boot (or if RTC was cleared)
  if (screenCount == 0) buildScreenList();

  const uint8_t screenId = screenList[bootCount % screenCount];
  ++bootCount;
  const esp_sleep_wakeup_cause_t wakeCause = esp_sleep_get_wakeup_cause();

  Serial.begin(115200);
  Serial0.begin(115200);
  MIN_VALID_EPOCH = buildDateEpoch();
  delay(SERIAL_WAIT_MS);

  logf("Boot #%lu screenId=%u wakeCause=%s",
       (unsigned long)(bootCount-1), (unsigned)screenId, wakeupCauseStr(wakeCause));
  logf("Build: %s %s  MIN_VALID_EPOCH=%lld",
       __DATE__, __TIME__, (long long)MIN_VALID_EPOCH);

  setupDisplay();
  initRgbLed();
  runDashboardCycle(screenId);

  if (CONTINUOUS_RGB_MODE) {
    continuousModeActive = true;
    activeCycle = bootCount % screenCount; // index into screenList for next render
    lastCycleRefreshMs = millis();
    logLine("Continuous RGB mode: staying awake");
    return;
  }

  runRgbSpectrum(POST_RENDER_LOG_MS);
  deepSleepUntilNextUpdate(getIntervalForScreen(screenId));
}

void loop() {
  if (!continuousModeActive) return;

  updateContinuousRgb();

  const uint8_t currentScreen = screenList[activeCycle % screenCount];
  const uint32_t refreshIntervalMs = getIntervalForScreen(currentScreen) * 1000UL;

  if (millis() - lastCycleRefreshMs >= refreshIntervalMs) {
    runDashboardCycle(currentScreen);
    ++bootCount;
    activeCycle = bootCount % screenCount;
    lastCycleRefreshMs = millis();
  }
  delay(RGB_LED_STEP_MS);
}
